[package]
name = "gatt-peripheral-android"
version.workspace = true
edition.workspace = true

[lib]
name = "gatt_peripheral_android"
crate-type = ["cdylib", "rlib"]

[features]
bindgen = ["uniffi/cli"]

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"
required-features = ["bindgen"]

[dependencies]
uniffi = "=0.31.0"
thiserror = "2"
futures-channel = "0.3"

[target.'cfg(target_os = "android")'.dependencies]
btstack-gatt = { path = "../../../btstack-gatt" }
btstack-nusb = { path = "../../../btstack-nusb" }
libc = "0.2"
